apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false 
        service:
          ui:
            type: NodePort
            nodePort: 30000
    repoURL: https://charts.longhorn.io
    targetRevision: 1.10.1
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true