expose:
  ingress:
    hosts:
      core: harbor.niyov.com

externalURL: https://harbor.niyov.com

persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-pvc
      subPath: registry
    jobservice:
      existingClaim: harbor-pvc
      subPath: jobservice
    database:
      existingClaim: harbor-pvc
      subPath: database
    redis:
      existingClaim: harbor-pvc
      subPath: redis
    trivy:
      existingClaim: harbor-pvc
      subPath: trivy
