apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-list-staging
spec:
  destination:
    name: ''
    namespace: todo-list-staging
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/Netanel-Iyov/Todo-List-Chart.git'
    targetRevision: v1.0.1
    helm:
      values: |
        global:
          namespace: todo-list-staging
        
        api:
          ingress:
            host: api-todo-list-staging.niyov.com
        
          deployment:
            apiContainer:
              image: harbor.niyov.com/applications/todo-list-api-staging:2.0.2
              requests:
                cpu: "200m"
              limits:
                cpu: "300m"
          
          hpa:
            minReplicas: 1
            maxReplicas: 3
            metrics:
              cpu:
                averageUtilization: 50
                
        client:
          ingress:
            host: todo-list-staging.niyov.com
        
          deployment:
            clientContainer:
              image: harbor.niyov.com/applications/todo-list-client-staging:2.0.2
              requests:
                cpu: "100m"
              limits:
                cpu: "150m"

          hpa:
            minReplicas: 1
            maxReplicas: 3
            metrics:
              cpu:
                averageUtilization: 50
        
        db:
          deployment:
            volumes:
              pv:
                name: todo-list-db-pv-staging
                hostPath: /nfs/volumes/todo-list-mongo-db-staging
              pvc:
                name: todo-list-db-pvc-staging
  sources: []
  project: todo-list
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
