apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-list-testing
spec:
  destination:
    name: ''
    namespace: todo-list-testing
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/Netanel-Iyov/Todo-List-Chart.git'
    targetRevision: niyov/add-testing-env
    helm:
      valueFiles:
        - values-testing.yaml
  sources: []
  project: todo-list
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
