apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-list-testing
spec:
  destination:
    name: ''
    namespace: todo-list-testing
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/Netanel-Iyov/Todo-List-Chart.git'
    targetRevision: niyov/add-hpa
    helm:
      values: |
        global:
          namespace: todo-list-testing
        
        api:
          ingress:
            host: api-todo-list-testing.niyov.com
        
          deployment:
            apiContainer:
              image: harbor.niyov.com/applications/todo-list-api-testing:f3aaffb9ea7a31eead5e1a4640fc73b7afbd377f
              requests:
                cpu: "200m"
              limits:
                cpu: "300m"
        
        client:
          ingress:
            host: todo-list-testing.niyov.com
          
          deployment:
            clientContainer:
              image: harbor.niyov.com/applications/todo-list-client-testing:f3aaffb9ea7a31eead5e1a4640fc73b7afbd377f
              requests:
                cpu: "100m"
              limits:
                cpu: "150m"

        db:
          deployment:
            volumes:
              pv:
                name: todo-list-db-pv-testing
                hostPath: /nfs/volumes/todo-list-mongo-db-testing
              pvc:
                name: todo-list-db-pvc-testing
  sources: []
  project: todo-list
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
