apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.8.133
    helm:
      releaseName: jenkins
      values: |
        persistence:
          enabled: true
          existingClaim: jenkins-pvc

        agent: 
          websocket: true

        controller:
          componentName: "jenkins-controller"
          serviceType: ClusterIP
          # Pod-level: Ensures the volume is mounted for GID 2000
          podSecurityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
          
          # Container-level: Forces the Jenkins process to start as 2000
          containerSecurityContext:
            runAsUser: 2000
            runAsGroup: 2000
          
          # This tells the init container (which fixes permissions) to use 2000
          initContainerEnv:
            - name: "DEFAULT_CHOWN"
              value: "false" # Prevents it from trying to chown back to 1000

            # Ensure the main controller also knows about the cache location
            - name: "CACHE_DIR"
              value: "/var/jenkins_home/.cache"

          # Ingress Configuration
          ingress:
            enabled: true
            ingressClassName: nginx
            apiVersion: "networking.k8s.io/v1"
            hostName: jenkins.niyov.com
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            tls:
              - secretName: niyov-wildcard-tls
                hosts:
                  - jenkins.niyov.com
          # Ensure Jenkins knows its external URL for redirects
          jenkinsUrl: "https://jenkins.niyov.com"
          installPlugins:
            - kubernetes
            - configuration-as-code
            - git
            - workflow-aggregator
            - credentials-binding
            - locale
            - job-dsl
            - envinject
          JCasC:
            defaultConfig: true
            configScripts:
              ui-settings: |
                jenkins:
                  systemMessage: "Welcome to my home-lab CI/CD platform. This Application is Managed by ArgoCD"
                appearance:
                  locale:
                    systemLocale: en
                    ignoreAcceptLanguage: true
                    allowUserPreferences: false

              k8s-integration: |
                jenkins:
                  clouds:
                    - kubernetes:
                        name: "niyov-k8s-cluster"
                        serverUrl: "https://kubernetes.default.svc.cluster.local"
                        namespace: "jenkins"
                        jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                        webSocket: true
                        templates:
                          - name: "default-k8s-agent"
                            label: "default-k8s-agent"
                            nodeUsageMode: NORMAL
                            containers:
                              - name: "jnlp"
                                image: "jenkins/inbound-agent:latest"
                              - name: "default-k8s-tools-container"
                                image: "alpine/k8s:1.29.1"
                                command: "cat"
                                ttyEnabled: true

              security: |
                security:
                  globalJobDslSecurityConfiguration:
                    useScriptSecurity: false

              seed-job: |
                jobs:
                  - script: >
                      pipelineJob('seed-job-dsl') {
                        description('Seeds Jenkins jobs from Job DSL repository')

                        definition {
                          cps {
                            script('''
                              pipeline {
                                agent { 
                                  label 'default-k8s-agent'
                                }

                                environment {
                                  PRODUCTION_ENV  = 'true'
                                }

                                stages {
                                  stage('Checkout DSL repo') {
                                    steps {
                                      git branch: "main", url: 'https://github.com/Netanel-Iyov/Jenkins-Dsl.git'
                                    }
                                  }

                                  stage('Seed jobs') {
                                    steps {
                                      jobDsl(
                                        targets: '**/DSL**.groovy',
                                        removedJobAction: 'DELETE',
                                        removedViewAction: 'DELETE',
                                        lookupStrategy: 'SEED_JOB',
                                        additionalParameters: [PRODUCTION_ENV: env.PRODUCTION_ENV]
                                      )
                                    }
                                  }
                                }
                              }
                            ''')
                          }
                        }
                      }
                  - script: queue('seed-job-dsl') 

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true