apiVersion: v1
kind: Secret
metadata:
 name: niyov-wildcard-tls
 namespace: jenkins
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "argocd/niyov-wildcard-tls"
   reflector.v1.k8s.emberstack.com/auto-reflects: "True"
type: kubernetes.io/tls
data: {}