apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus-stack
    server: https://kubernetes.default.svc
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: '71.2.0'
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
              - job_name: jenkins
                metrics_path: /prometheus/
                static_configs:
                - targets:
                  - jenkins.niyov.com

        prometheusOperator:
          admissionWebhooks:
            enabled: true

            annotations:
              argocd.argoproj.io/hook: PostSync
              argocd.argoproj.io/hook-delete-policy: HookSucceeded

            patch:
              annotations:
                argocd.argoproj.io/hook: PostSync
                argocd.argoproj.io/hook-delete-policy: HookSucceeded
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
