apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-default-storageclass
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.221 # NFS Server
  share: /nfs/k8s-data
  subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}
reclaimPolicy: Retain  # "Retain" is safer for production data
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard           # Retries indefinitely if the server goes down
  - timeo=600      # Wait 60s before retrying
  - retrans=2      # Number of retries