apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.goharbor.io"
    targetRevision: 1.18.2
    helm:
      releaseName: harbor
      values: |
        expose:
          tls:
            certSource: secret
            secret:
              secretName: niyov-wildcard-tls
          ingress:
            hosts:
              core: harbor.niyov.com
            annotations: 
              kubernetes.io/ingress.class: "nginx"
              ingress.kubernetes.io/ssl-redirect: "false"
              ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
        externalURL: https://harbor.niyov.com
        persistence:
          enabled: true
          resourceDefaultStorageClass: "nfs-csi-deafult-storageclass"
          persistentVolumeClaim:
            registry:
              size: 10Gi
            jobservice:
              jobLog:
                size: 500Mi
            database:
              size: 1Gi
            redis:
              size: 500Mi    # Minimal: Just caching/session data
            trivy:
              size: 2Gi
    chart: harbor
  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
