apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  sources:
    - chart: harbor
      repoURL: "https://helm.goharbor.io"
      targetRevision: 1.16.0
      helm:
        valuesFiles:
          - $values/infrastructure-apps/harbor/values.yml
    # Values sourced from git
    - repoURL: 'https://github.com/Netanel-Iyov/ArgoCD-GitOps'
      targetRevision: main
      ref: values 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true