apiVersion: v1
kind: PersistentVolume
metadata:
  name: hashi-corp-vault-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    # Many nodes can mount it as read-write
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /nfs/data/hashi-corp-vault