apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: winning-horse-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Netanel-Iyov/winning-horse-app.git
    targetRevision: main
    path: deploy/helm/winning-horse
    helm:
      values: |
        global:
          namespace: winning-horse-staging
        api:
          image:
            tag: 1.0.0
          corsOrigins: https://winning-horse-staging.niyov.com
        frontend:
          image:
            tag: 1.0.0
        ingress:
          frontendHost: winning-horse-staging.niyov.com
          apiHost: api-winning-horse-staging.niyov.com
  destination:
    server: https://kubernetes.default.svc
    namespace: winning-horse-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
